/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import controller.Controller;
import domain.Manufacturer;
import domain.Product;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import ui.component.table.model.ProductTableModel;

/**
 *
 * @author Dusan
 */
public class FProductSearch extends javax.swing.JDialog {

    /**
     * Creates new form FProductSearch
     */
    public FProductSearch(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(null);

        fillForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblProducts = new javax.swing.JTable();
        jbtnDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search product...");

        jtblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Manufacturer", "Price", "Measurement Unit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblProducts);

        jbtnDetails.setText("Details");
        jbtnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnDetails)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = jtblProducts.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select product");
        } else {
            try {
                FProduct form = new FProduct(null, true, FormMode.FORM_VIEW);
                form.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(FProductSearch.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbtnDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDetails;
    private javax.swing.JTable jtblProducts;
    // End of variables declaration//GEN-END:variables

    private void fillForm() throws Exception {
        List<Product> products = Controller.getInstance().getAllProducts();
        jtblProducts.setModel(new ProductTableModel(products));

        List<Manufacturer> manufacturers = Controller.getInstance().getAllManufacturers();
        JComboBox jcomboManufacturer = new JComboBox(new DefaultComboBoxModel(manufacturers.toArray()));
        TableColumn tc = jtblProducts.getColumnModel().getColumn(2);
        tc.setCellEditor(new DefaultCellEditor(jcomboManufacturer));
//        TableModel tm = jtblProducts.getModel();
//        DefaultTableModel dtm = (DefaultTableModel)tm;
//        for (Product product : products) {
//            Object[] data = new Object[5];
//            data[0] = product.getId();
//            data[1] = product.getName();
//            data[2] = product.getManufacturer();
//            data[3] = product.getPrice();
//            data[4] = product.getMeasurementUnit();
//            dtm.addRow(data);
//        }
    }
}
